language: node_js
node_js:
  - 8
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &   # nohup - if the shell closed, don't kill anything | & run this command in a subshell(background)
  - sleep 3
  - npm run test